name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository dengan HTTPS
      - name: Checkout repository
        uses: actions/checkout@v3

      # Jalankan perintah setup (contoh Node.js)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Jalankan tes
      - name: Run tests
        run: npm test

